# Generated by Django 3.2 on 2021-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_hostel_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=6),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('vacant', 'Vacant')], default='vacant', max_length=8),
        ),
    ]
