# Generated by Django 3.2 on 2021-06-01 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210421_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='room_limit',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
